# Taller importación y extracción de datos

En este notebook se desarrolla el taller solicitado. Se carga la base del World Economic Outlook (WEO) del FMI, se consulta la API del Banco Mundial para obtener datos de inflación de seis países y cinco indicadores macroeconómicos para Alemania, se utiliza la API del portal de datos abiertos del Gobierno de Colombia y finalmente se consulta una API adicional para cargar otro conjunto de datos.

#1.

In [11]:
url = "https://api.worldbank.org/v2/country/COL/indicator/FP.CPI.TOTL.ZG?format=json&date=2010:2023&per_page=100"
print(url)

https://api.worldbank.org/v2/country/COL/indicator/FP.CPI.TOTL.ZG?format=json&date=2010:2023&per_page=100

In [4]:
"/content/weoapr2025all.xls"

'/content/weoapr2025all.xls'

In [28]:
!pip install xlrd openpyxl requests pandas

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [29]:
import pandas as pd
import requests

In [32]:
ruta = "/content/weoapr2025all.xls"

for enc in ["utf-16le", "utf-16", "latin1", "utf-8"]:
    try:
        weo = pd.read_csv(ruta, sep="\t", encoding=enc, engine="python")
        print("Funcionó con:", enc)
        break
    except Exception as e:
        print("Falló con", enc, "->", e)

weo.head()

Funcionó con: utf-16le

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After,Unnamed: 61
0,512,AFG,NGDP_R,Afghanistan,"Gross domestic product, constant prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,056.123",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
1,512,AFG,NGDP_RPCH,Afghanistan,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,Units,"See notes for: Gross domestic product, consta...",NaN,...,2.267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
2,512,AFG,NGDP,Afghanistan,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,350.910",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
3,512,AFG,NGDPD,Afghanistan,"Gross domestic product, current prices",Values are based upon GDP in national currency...,U.S. dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,17.248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,91.272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN

In [33]:
print("Primeras 5 filas")
display(weo.head())

print("Últimas 10 filas")
display(weo.tail(10))

print("3 filas aleatorias")
display(weo.sample(min(3, len(weo)), random_state=42))

print("Fila 2 a la 5 y solamente la segunda columna")
display(weo.iloc[1:5, [1]])

print("Número de filas con len()")
print(len(weo))

print("Número de filas y columnas con shape")
print(weo.shape)

print("Nombres de las columnas")
print(weo.columns)

print("Tipo de dato de cada columna")
print(weo.dtypes)

print("Información general del conjunto de datos")
weo.info()

Primeras 5 filas

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After,Unnamed: 61
0,512,AFG,NGDP_R,Afghanistan,"Gross domestic product, constant prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,056.123",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
1,512,AFG,NGDP_RPCH,Afghanistan,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,Units,"See notes for: Gross domestic product, consta...",NaN,...,2.267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
2,512,AFG,NGDP,Afghanistan,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,350.910",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
3,512,AFG,NGDPD,Afghanistan,"Gross domestic product, current prices",Values are based upon GDP in national currency...,U.S. dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,17.248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,91.272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN

Últimas 10 filas

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After,Unnamed: 61
8615,698,ZWE,GGXONLB,Zimbabwe,General government primary net lending/borrowing,Primary net lending/borrowing is net lending (...,National currency,Billions,Source: Ministry of Finance or Treasury Latest...,NaN,...,-2.782,-6.462,6.178,20.180,28.764,33.448,38.866,43.344,2024.0,NaN
8616,698,ZWE,GGXONLB_NGDP,Zimbabwe,General government primary net lending/borrowing,Primary net lending/borrowing is net lending (...,Percent of GDP,Units,See notes for: General government primary net...,NaN,...,-5.198,-1.096,0.537,1.529,1.948,2.028,2.108,2.108,2024.0,NaN
8617,698,ZWE,GGXWDN,Zimbabwe,General government net debt,Net debt is calculated as gross debt minus fin...,National currency,Billions,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8618,698,ZWE,GGXWDN_NGDP,Zimbabwe,General government net debt,Net debt is calculated as gross debt minus fin...,Percent of GDP,Units,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8619,698,ZWE,GGXWDG,Zimbabwe,General government gross debt,Gross debt consists of all liabilities that re...,National currency,Billions,Source: Ministry of Finance or Treasury Latest...,NaN,...,51.682,557.793,673.344,739.670,786.902,862.793,930.773,993.329,2024.0,NaN
8620,698,ZWE,GGXWDG_NGDP,Zimbabwe,General government gross debt,Gross debt consists of all liabilities that re...,Percent of GDP,Units,See notes for: General government gross debt ...,NaN,...,96.586,94.587,58.568,56.051,53.294,52.315,50.485,48.312,2024.0,NaN
8621,698,ZWE,NGDP_FY,Zimbabwe,Gross domestic product corresponding to fiscal...,Gross domestic product corresponding to fiscal...,National currency,Billions,Source: Ministry of Finance or Treasury Latest...,NaN,...,53.509,589.716,"1,149.685","1,319.643","1,476.529","1,649.212","1,843.656","2,056.061",2024.0,NaN
8622,698,ZWE,BCA,Zimbabwe,Current account balance,Current account is all transactions other than...,U.S. dollars,Billions,Source: Reserve Bank of Zimbabwe and Ministry ...,-0.301,...,0.135,0.505,1.143,1.210,1.198,1.226,1.120,0.996,2023.0,NaN
8623,698,ZWE,BCA_NGDPD,Zimbabwe,Current account balance,Current account is all transactions other than...,Percent of GDP,Units,"See notes for: Gross domestic product, curren...",NaN,...,0.384,1.435,2.994,3.063,2.927,2.895,2.554,2.196,2023.0,NaN
8624,"International Monetary Fund, World Economic Ou...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,NaN,NaN

3 filas aleatorias

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After,Unnamed: 61
3590,178,IRL,LP,Ireland,Population,"For census purposes, the total population of t...",Persons,Millions,Source: National Statistics Office. Central St...,3.426,...,5.331,5.422,5.498,5.558,5.609,5.642,5.675,5.709,2024.0,NaN
222,311,ATG,NGDP,Antigua and Barbuda,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: Central Bank Latest actual data: 2022....,0.358,...,5.416,6.007,6.408,6.731,7.037,7.353,7.684,8.030,2022.0,NaN
7030,733,SSD,GGSB_NPGDP,South Sudan,General government structural balance,The structural budget balance refers to the ge...,Percent of potential GDP,Units,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Fila 2 a la 5 y solamente la segunda columna

   ISO
1  AFG
2  AFG
3  AFG
4  AFG

Número de filas con len()
8625
Número de filas y columnas con shape
(8625, 62)
Nombres de las columnas
Index(['WEO Country Code', 'ISO', 'WEO Subject Code', 'Country',
       'Subject Descriptor', 'Subject Notes', 'Units', 'Scale',
       'Country/Series-specific Notes', '1980', '1981', '1982', '1983', '1984',
       '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029',
       '2030', 'Estimates Start After', 'Unnamed: 61'],
      dtype='object')
Tipo de dato de cada columna
WEO Country Code          object
ISO                       object
WEO Subject Code          object
Country                   object
Subject Descriptor        object
                          ...
2028                      object
2029                      object
2030                      object
Estimates Start After    float64
Unnamed: 61              float64
Length: 62, dtype: object
Información general del conjunto de datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8625 entries, 0 to 8624
Data columns (total 62 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   WEO Country Code               8625 non-null   object
 1   ISO                            8624 non-null   object
 2   WEO Subject Code               8624 non-null   object
 3   Country                        8624 non-null   object
 4   Subject Descriptor             8624 non-null   object
 5   Subject Notes                  8624 non-null   object
 6   Units                          8624 non-null   object
 7   Scale                          8624 non-null   object
 8   Country/Series-specific Notes  7648 non-null   object
 9   1980                           3861 non-null   object
 10  1981                           3995 non-null   object
 11  1982                           4039 non-null   object
 12  1983                           4079 non-null   object
 13  1984                           4104 non-null   object
 14  1985                           4187 non-null   object
 15  1986                           4235 non-null   object
 16  1987                           4259 non-null   object
 17  1988                           4348 non-null   object
 18  1989                           4409 non-null   object
 19  1990                           4889 non-null   object
 20  1991                           5049 non-null   object
 21  1992                           5435 non-null   object
 22  1993                           5635 non-null   object
 23  1994                           5762 non-null   object
 24  1995                           6108 non-null   object
 25  1996                           6242 non-null   object
 26  1997                           6404 non-null   object
 27  1998                           6565 non-null   object
 28  1999                           6659 non-null   object
 29  2000                           7086 non-null   object
 30  2001                           7236 non-null   object
 31  2002                           7329 non-null   object
 32  2003                           7357 non-null   object
 33  2004                           7427 non-null   object
 34  2005                           7460 non-null   object
 35  2006                           7467 non-null   object
 36  2007                           7469 non-null   object
 37  2008                           7478 non-null   object
 38  2009                           7499 non-null   object
 39  2010                           7512 non-null   object
 40  2011                           7517 non-null   object
 41  2012                           7536 non-null   object
 42  2013                           7554 non-null   object
 43  2014                           7578 non-null   object
 44  2015                           7592 non-null   object
 45  2016                           7594 non-null   object
 46  2017                           7599 non-null   object
 47  2018                           7597 non-null   object
 48  2019                           7597 non-null   object
 49  2020                           7560 non-null   object
 50  2021                           7560 non-null   object
 51  2022                           7560 non-null   object
 52  2023                           7557 non-null   object
 53  2024                           7485 non-null   object
 54  2025                           7371 non-null   object
 55  2026                           7371 non-null   object
 56  2027                           7246 non-null   object
 57  2028                           7246 non-null   object
 58  2029                           7246 non-null   object
 59  2030                           7246 non-null   object
 60  Estimates Start After          7648 non-null   float64
 61  Unnamed: 61                    0 non-null      float64
dtypes: float64(2), object(60)
memory usage: 4.1+ MB

##2

In [34]:
paises = {
    "COL": "Colombia",
    "ECU": "Ecuador",
    "BRA": "Brasil",
    "CHL": "Chile",
    "MEX": "México",
    "PER": "Perú"
}

indicador = "FP.CPI.TOTL.ZG"
lista = []

for codigo, nombre in paises.items():
    url = f"https://api.worldbank.org/v2/country/{codigo}/indicator/{indicador}?format=json&date=2010:2023&per_page=100"
    respuesta = requests.get(url)
    data = respuesta.json()

    df_temp = pd.json_normalize(data[1])
    df_temp = df_temp[["date", "value"]].copy()
    df_temp["pais"] = nombre
    df_temp.columns = ["anio", "inflacion", "pais"]
    lista.append(df_temp)

inflacion = pd.concat(lista, ignore_index=True)
inflacion = inflacion[["pais", "anio", "inflacion"]]
inflacion["anio"] = pd.to_numeric(inflacion["anio"], errors="coerce")
inflacion = inflacion.sort_values(["pais", "anio"]).reset_index(drop=True)

inflacion.head()

     pais  anio  inflacion
0  Brasil  2010   5.038727
1  Brasil  2011   6.636450
2  Brasil  2012   5.403499
3  Brasil  2013   6.204311
4  Brasil  2014   6.329040

In [35]:
display(inflacion.head())
display(inflacion.tail(10))
display(inflacion.sample(min(3, len(inflacion)), random_state=42))
display(inflacion.iloc[1:5, [1]])

print("len:", len(inflacion))
print("shape:", inflacion.shape)
print("columns:", inflacion.columns)
print("dtypes:")
print(inflacion.dtypes)
inflacion.info()

     pais  anio  inflacion
0  Brasil  2010   5.038727
1  Brasil  2011   6.636450
2  Brasil  2012   5.403499
3  Brasil  2013   6.204311
4  Brasil  2014   6.329040

    pais  anio  inflacion
74  Perú  2014   3.411946
75  Perú  2015   3.398092
76  Perú  2016   3.557177
77  Perú  2017   2.994900
78  Perú  2018   1.509154
79  Perú  2019   2.252122
80  Perú  2020   2.002412
81  Perú  2021   4.271664
82  Perú  2022   8.333706
83  Perú  2023   6.455613

      pais  anio  inflacion
73    Perú  2013   2.767897
0   Brasil  2010   5.038727
58  México  2012   4.111510

   anio
1  2011
2  2012
3  2013
4  2014

len: 84
shape: (84, 3)
columns: Index(['pais', 'anio', 'inflacion'], dtype='object')
dtypes:
pais          object
anio           int64
inflacion    float64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pais       84 non-null     object
 1   anio       84 non-null     int64
 2   inflacion  84 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.1+ KB

###3

In [36]:
indicadores_alemania = {
    "NY.GDP.MKTP.KD.ZG": "crecimiento_pib",
    "NY.GDP.PCAP.PP.CD": "pib_percapita_ppa",
    "FP.CPI.TOTL.ZG": "inflacion",
    "SL.UEM.TOTL.ZS": "desempleo",
    "SP.POP.TOTL": "poblacion"
}

lista = []

for codigo_ind, nombre_ind in indicadores_alemania.items():
    url = f"https://api.worldbank.org/v2/country/DEU/indicator/{codigo_ind}?format=json&date=2010:2023&per_page=100"
    respuesta = requests.get(url)
    data = respuesta.json()

    df_temp = pd.json_normalize(data[1])
    df_temp = df_temp[["date", "value"]].copy()
    df_temp.columns = ["anio", nombre_ind]
    df_temp["anio"] = pd.to_numeric(df_temp["anio"], errors="coerce")
    lista.append(df_temp)

alemania = lista[0]
for df in lista[1:]:
    alemania = alemania.merge(df, on="anio", how="outer")

alemania = alemania.sort_values("anio").reset_index(drop=True)

alemania.head()

   anio  crecimiento_pib  pib_percapita_ppa  inflacion  desempleo  poblacion
0  2010         4.134638       39726.098692   1.103810      7.043   81776930
1  2011         3.757969       43398.344399   2.075173      5.967   80274983
2  2012         0.463512       44229.394192   2.008489      5.372   80425823
3  2013         0.396996       45889.017302   1.504723      5.316   80645605
4  2014         2.180186       47938.796821   0.906794      4.979   80982500

In [37]:
display(alemania.head())
display(alemania.tail(10))
display(alemania.sample(min(3, len(alemania)), random_state=42))
display(alemania.iloc[1:5, [1]])

print("len:", len(alemania))
print("shape:", alemania.shape)
print("columns:", alemania.columns)
print("dtypes:")
print(alemania.dtypes)
alemania.info()

   anio  crecimiento_pib  pib_percapita_ppa  inflacion  desempleo  poblacion
0  2010         4.134638       39726.098692   1.103810      7.043   81776930
1  2011         3.757969       43398.344399   2.075173      5.967   80274983
2  2012         0.463512       44229.394192   2.008489      5.372   80425823
3  2013         0.396996       45889.017302   1.504723      5.316   80645605
4  2014         2.180186       47938.796821   0.906794      4.979   80982500

    anio  crecimiento_pib  pib_percapita_ppa  inflacion  desempleo  poblacion
4   2014         2.180186       47938.796821   0.906794      4.979   80982500
5   2015         1.663006       48545.400722   0.514426      4.612   81686611
6   2016         2.222222       51569.901684   0.491747      4.104   82348669
7   2017         2.797907       54110.253665   1.509495      3.781   82657002
8   2018         1.135696       56273.040563   1.732169      3.384   82905782
9   2019         0.977735       59270.727650   1.445660      3.163   83092962
10  2020        -4.131914       58685.872700   0.144878      3.881   83160871
11  2021         3.910000       62530.765320   3.066667      3.594   83196078
12  2022         1.809258       69048.988404   6.872574      3.137   83177813
13  2023        -0.869648       71684.031188   5.946437      3.071   83287273

    anio  crecimiento_pib  pib_percapita_ppa  inflacion  desempleo  poblacion
9   2019         0.977735       59270.727650   1.445660      3.163   83092962
11  2021         3.910000       62530.765320   3.066667      3.594   83196078
0   2010         4.134638       39726.098692   1.103810      7.043   81776930

   crecimiento_pib
1         3.757969
2         0.463512
3         0.396996
4         2.180186

len: 14
shape: (14, 6)
columns: Index(['anio', 'crecimiento_pib', 'pib_percapita_ppa', 'inflacion',
       'desempleo', 'poblacion'],
      dtype='object')
dtypes:
anio                   int64
crecimiento_pib      float64
pib_percapita_ppa    float64
inflacion            float64
desempleo            float64
poblacion              int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   anio               14 non-null     int64
 1   crecimiento_pib    14 non-null     float64
 2   pib_percapita_ppa  14 non-null     float64
 3   inflacion          14 non-null     float64
 4   desempleo          14 non-null     float64
 5   poblacion          14 non-null     int64
dtypes: float64(4), int64(2)
memory usage: 804.0 bytes

####4

In [38]:
!pip install pandas requests openpyxl xlrd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [39]:
import pandas as pd
import requests

In [40]:
ruta = "/content/weoapr2025all.xls"

weo = None
for enc in ["utf-16le", "utf-16", "latin1", "utf-8"]:
    try:
        weo = pd.read_csv(ruta, sep="\t", encoding=enc, engine="python")
        print("Funcionó con:", enc)
        break
    except Exception as e:
        print("Falló con", enc, "->", e)

weo.head()

Funcionó con: utf-16le

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After,Unnamed: 61
0,512,AFG,NGDP_R,Afghanistan,"Gross domestic product, constant prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,056.123",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
1,512,AFG,NGDP_RPCH,Afghanistan,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,Units,"See notes for: Gross domestic product, consta...",NaN,...,2.267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
2,512,AFG,NGDP,Afghanistan,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,350.910",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
3,512,AFG,NGDPD,Afghanistan,"Gross domestic product, current prices",Values are based upon GDP in national currency...,U.S. dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,17.248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,91.272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN

In [41]:
print("Primeras 5 filas")
display(weo.head())

print("Últimas 10 filas")
display(weo.tail(10))

print("3 filas aleatorias")
display(weo.sample(min(3, len(weo)), random_state=42))

print("Filas 2 a 5 y solo la segunda columna")
display(weo.iloc[1:5, [1]])

print("len:")
print(len(weo))

print("shape:")
print(weo.shape)

print("columns:")
print(weo.columns)

print("dtypes:")
print(weo.dtypes)

print("info():")
weo.info()

Primeras 5 filas

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After,Unnamed: 61
0,512,AFG,NGDP_R,Afghanistan,"Gross domestic product, constant prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,056.123",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
1,512,AFG,NGDP_RPCH,Afghanistan,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,Units,"See notes for: Gross domestic product, consta...",NaN,...,2.267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
2,512,AFG,NGDP,Afghanistan,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,350.910",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
3,512,AFG,NGDPD,Afghanistan,"Gross domestic product, current prices",Values are based upon GDP in national currency...,U.S. dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,17.248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN
4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,91.272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,NaN

Últimas 10 filas

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After,Unnamed: 61
8615,698,ZWE,GGXONLB,Zimbabwe,General government primary net lending/borrowing,Primary net lending/borrowing is net lending (...,National currency,Billions,Source: Ministry of Finance or Treasury Latest...,NaN,...,-2.782,-6.462,6.178,20.180,28.764,33.448,38.866,43.344,2024.0,NaN
8616,698,ZWE,GGXONLB_NGDP,Zimbabwe,General government primary net lending/borrowing,Primary net lending/borrowing is net lending (...,Percent of GDP,Units,See notes for: General government primary net...,NaN,...,-5.198,-1.096,0.537,1.529,1.948,2.028,2.108,2.108,2024.0,NaN
8617,698,ZWE,GGXWDN,Zimbabwe,General government net debt,Net debt is calculated as gross debt minus fin...,National currency,Billions,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8618,698,ZWE,GGXWDN_NGDP,Zimbabwe,General government net debt,Net debt is calculated as gross debt minus fin...,Percent of GDP,Units,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8619,698,ZWE,GGXWDG,Zimbabwe,General government gross debt,Gross debt consists of all liabilities that re...,National currency,Billions,Source: Ministry of Finance or Treasury Latest...,NaN,...,51.682,557.793,673.344,739.670,786.902,862.793,930.773,993.329,2024.0,NaN
8620,698,ZWE,GGXWDG_NGDP,Zimbabwe,General government gross debt,Gross debt consists of all liabilities that re...,Percent of GDP,Units,See notes for: General government gross debt ...,NaN,...,96.586,94.587,58.568,56.051,53.294,52.315,50.485,48.312,2024.0,NaN
8621,698,ZWE,NGDP_FY,Zimbabwe,Gross domestic product corresponding to fiscal...,Gross domestic product corresponding to fiscal...,National currency,Billions,Source: Ministry of Finance or Treasury Latest...,NaN,...,53.509,589.716,"1,149.685","1,319.643","1,476.529","1,649.212","1,843.656","2,056.061",2024.0,NaN
8622,698,ZWE,BCA,Zimbabwe,Current account balance,Current account is all transactions other than...,U.S. dollars,Billions,Source: Reserve Bank of Zimbabwe and Ministry ...,-0.301,...,0.135,0.505,1.143,1.210,1.198,1.226,1.120,0.996,2023.0,NaN
8623,698,ZWE,BCA_NGDPD,Zimbabwe,Current account balance,Current account is all transactions other than...,Percent of GDP,Units,"See notes for: Gross domestic product, curren...",NaN,...,0.384,1.435,2.994,3.063,2.927,2.895,2.554,2.196,2023.0,NaN
8624,"International Monetary Fund, World Economic Ou...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,NaN,NaN

3 filas aleatorias

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After,Unnamed: 61
3590,178,IRL,LP,Ireland,Population,"For census purposes, the total population of t...",Persons,Millions,Source: National Statistics Office. Central St...,3.426,...,5.331,5.422,5.498,5.558,5.609,5.642,5.675,5.709,2024.0,NaN
222,311,ATG,NGDP,Antigua and Barbuda,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: Central Bank Latest actual data: 2022....,0.358,...,5.416,6.007,6.408,6.731,7.037,7.353,7.684,8.030,2022.0,NaN
7030,733,SSD,GGSB_NPGDP,South Sudan,General government structural balance,The structural budget balance refers to the ge...,Percent of potential GDP,Units,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Filas 2 a 5 y solo la segunda columna

   ISO
1  AFG
2  AFG
3  AFG
4  AFG

len:
8625
shape:
(8625, 62)
columns:
Index(['WEO Country Code', 'ISO', 'WEO Subject Code', 'Country',
       'Subject Descriptor', 'Subject Notes', 'Units', 'Scale',
       'Country/Series-specific Notes', '1980', '1981', '1982', '1983', '1984',
       '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029',
       '2030', 'Estimates Start After', 'Unnamed: 61'],
      dtype='object')
dtypes:
WEO Country Code          object
ISO                       object
WEO Subject Code          object
Country                   object
Subject Descriptor        object
                          ...
2028                      object
2029                      object
2030                      object
Estimates Start After    float64
Unnamed: 61              float64
Length: 62, dtype: object
info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8625 entries, 0 to 8624
Data columns (total 62 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   WEO Country Code               8625 non-null   object
 1   ISO                            8624 non-null   object
 2   WEO Subject Code               8624 non-null   object
 3   Country                        8624 non-null   object
 4   Subject Descriptor             8624 non-null   object
 5   Subject Notes                  8624 non-null   object
 6   Units                          8624 non-null   object
 7   Scale                          8624 non-null   object
 8   Country/Series-specific Notes  7648 non-null   object
 9   1980                           3861 non-null   object
 10  1981                           3995 non-null   object
 11  1982                           4039 non-null   object
 12  1983                           4079 non-null   object
 13  1984                           4104 non-null   object
 14  1985                           4187 non-null   object
 15  1986                           4235 non-null   object
 16  1987                           4259 non-null   object
 17  1988                           4348 non-null   object
 18  1989                           4409 non-null   object
 19  1990                           4889 non-null   object
 20  1991                           5049 non-null   object
 21  1992                           5435 non-null   object
 22  1993                           5635 non-null   object
 23  1994                           5762 non-null   object
 24  1995                           6108 non-null   object
 25  1996                           6242 non-null   object
 26  1997                           6404 non-null   object
 27  1998                           6565 non-null   object
 28  1999                           6659 non-null   object
 29  2000                           7086 non-null   object
 30  2001                           7236 non-null   object
 31  2002                           7329 non-null   object
 32  2003                           7357 non-null   object
 33  2004                           7427 non-null   object
 34  2005                           7460 non-null   object
 35  2006                           7467 non-null   object
 36  2007                           7469 non-null   object
 37  2008                           7478 non-null   object
 38  2009                           7499 non-null   object
 39  2010                           7512 non-null   object
 40  2011                           7517 non-null   object
 41  2012                           7536 non-null   object
 42  2013                           7554 non-null   object
 43  2014                           7578 non-null   object
 44  2015                           7592 non-null   object
 45  2016                           7594 non-null   object
 46  2017                           7599 non-null   object
 47  2018                           7597 non-null   object
 48  2019                           7597 non-null   object
 49  2020                           7560 non-null   object
 50  2021                           7560 non-null   object
 51  2022                           7560 non-null   object
 52  2023                           7557 non-null   object
 53  2024                           7485 non-null   object
 54  2025                           7371 non-null   object
 55  2026                           7371 non-null   object
 56  2027                           7246 non-null   object
 57  2028                           7246 non-null   object
 58  2029                           7246 non-null   object
 59  2030                           7246 non-null   object
 60  Estimates Start After          7648 non-null   float64
 61  Unnamed: 61                    0 non-null      float64
dtypes: float64(2), object(60)
memory usage: 4.1+ MB

In [42]:
paises = {
    "COL": "Colombia",
    "ECU": "Ecuador",
    "BRA": "Brasil",
    "CHL": "Chile",
    "MEX": "México",
    "PER": "Perú"
}

indicador = "FP.CPI.TOTL.ZG"
lista = []

for codigo, nombre in paises.items():
    url = f"https://api.worldbank.org/v2/country/{codigo}/indicator/{indicador}?format=json&date=2010:2023&per_page=100"
    respuesta = requests.get(url)
    data = respuesta.json()

    df_temp = pd.json_normalize(data[1])
    df_temp = df_temp[["date", "value"]].copy()
    df_temp["pais"] = nombre
    df_temp.columns = ["anio", "inflacion", "pais"]

    lista.append(df_temp)

inflacion = pd.concat(lista, ignore_index=True)
inflacion = inflacion[["pais", "anio", "inflacion"]]
inflacion["anio"] = pd.to_numeric(inflacion["anio"], errors="coerce")
inflacion = inflacion.sort_values(["pais", "anio"]).reset_index(drop=True)

inflacion.head()

     pais  anio  inflacion
0  Brasil  2010   5.038727
1  Brasil  2011   6.636450
2  Brasil  2012   5.403499
3  Brasil  2013   6.204311
4  Brasil  2014   6.329040

In [43]:
print("Primeras 5 filas")
display(inflacion.head())

print("Últimas 10 filas")
display(inflacion.tail(10))

print("3 filas aleatorias")
display(inflacion.sample(min(3, len(inflacion)), random_state=42))

print("Filas 2 a 5 y solo la segunda columna")
display(inflacion.iloc[1:5, [1]])

print("len:")
print(len(inflacion))

print("shape:")
print(inflacion.shape)

print("columns:")
print(inflacion.columns)

print("dtypes:")
print(inflacion.dtypes)

print("info():")
inflacion.info()

Primeras 5 filas

     pais  anio  inflacion
0  Brasil  2010   5.038727
1  Brasil  2011   6.636450
2  Brasil  2012   5.403499
3  Brasil  2013   6.204311
4  Brasil  2014   6.329040

Últimas 10 filas

    pais  anio  inflacion
74  Perú  2014   3.411946
75  Perú  2015   3.398092
76  Perú  2016   3.557177
77  Perú  2017   2.994900
78  Perú  2018   1.509154
79  Perú  2019   2.252122
80  Perú  2020   2.002412
81  Perú  2021   4.271664
82  Perú  2022   8.333706
83  Perú  2023   6.455613

3 filas aleatorias

      pais  anio  inflacion
73    Perú  2013   2.767897
0   Brasil  2010   5.038727
58  México  2012   4.111510

Filas 2 a 5 y solo la segunda columna

   anio
1  2011
2  2012
3  2013
4  2014

len:
84
shape:
(84, 3)
columns:
Index(['pais', 'anio', 'inflacion'], dtype='object')
dtypes:
pais          object
anio           int64
inflacion    float64
dtype: object
info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pais       84 non-null     object
 1   anio       84 non-null     int64
 2   inflacion  84 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.1+ KB

In [44]:
indicadores_alemania = {
    "NY.GDP.MKTP.KD.ZG": "crecimiento_pib",
    "NY.GDP.PCAP.PP.CD": "pib_percapita_ppa",
    "FP.CPI.TOTL.ZG": "inflacion",
    "SL.UEM.TOTL.ZS": "desempleo",
    "SP.POP.TOTL": "poblacion"
}

lista = []

for codigo_ind, nombre_ind in indicadores_alemania.items():
    url = f"https://api.worldbank.org/v2/country/DEU/indicator/{codigo_ind}?format=json&date=2010:2023&per_page=100"
    respuesta = requests.get(url)
    data = respuesta.json()

    df_temp = pd.json_normalize(data[1])
    df_temp = df_temp[["date", "value"]].copy()
    df_temp.columns = ["anio", nombre_ind]
    df_temp["anio"] = pd.to_numeric(df_temp["anio"], errors="coerce")

    lista.append(df_temp)

alemania = lista[0]
for df in lista[1:]:
    alemania = alemania.merge(df, on="anio", how="outer")

alemania = alemania.sort_values("anio").reset_index(drop=True)

alemania.head()

   anio  crecimiento_pib  pib_percapita_ppa  inflacion  desempleo  poblacion
0  2010         4.134638       39726.098692   1.103810      7.043   81776930
1  2011         3.757969       43398.344399   2.075173      5.967   80274983
2  2012         0.463512       44229.394192   2.008489      5.372   80425823
3  2013         0.396996       45889.017302   1.504723      5.316   80645605
4  2014         2.180186       47938.796821   0.906794      4.979   80982500

In [45]:
print("Primeras 5 filas")
display(alemania.head())

print("Últimas 10 filas")
display(alemania.tail(10))

print("3 filas aleatorias")
display(alemania.sample(min(3, len(alemania)), random_state=42))

print("Filas 2 a 5 y solo la segunda columna")
display(alemania.iloc[1:5, [1]])

print("len:")
print(len(alemania))

print("shape:")
print(alemania.shape)

print("columns:")
print(alemania.columns)

print("dtypes:")
print(alemania.dtypes)

print("info():")
alemania.info()

Primeras 5 filas

   anio  crecimiento_pib  pib_percapita_ppa  inflacion  desempleo  poblacion
0  2010         4.134638       39726.098692   1.103810      7.043   81776930
1  2011         3.757969       43398.344399   2.075173      5.967   80274983
2  2012         0.463512       44229.394192   2.008489      5.372   80425823
3  2013         0.396996       45889.017302   1.504723      5.316   80645605
4  2014         2.180186       47938.796821   0.906794      4.979   80982500

Últimas 10 filas

    anio  crecimiento_pib  pib_percapita_ppa  inflacion  desempleo  poblacion
4   2014         2.180186       47938.796821   0.906794      4.979   80982500
5   2015         1.663006       48545.400722   0.514426      4.612   81686611
6   2016         2.222222       51569.901684   0.491747      4.104   82348669
7   2017         2.797907       54110.253665   1.509495      3.781   82657002
8   2018         1.135696       56273.040563   1.732169      3.384   82905782
9   2019         0.977735       59270.727650   1.445660      3.163   83092962
10  2020        -4.131914       58685.872700   0.144878      3.881   83160871
11  2021         3.910000       62530.765320   3.066667      3.594   83196078
12  2022         1.809258       69048.988404   6.872574      3.137   83177813
13  2023        -0.869648       71684.031188   5.946437      3.071   83287273

3 filas aleatorias

    anio  crecimiento_pib  pib_percapita_ppa  inflacion  desempleo  poblacion
9   2019         0.977735       59270.727650   1.445660      3.163   83092962
11  2021         3.910000       62530.765320   3.066667      3.594   83196078
0   2010         4.134638       39726.098692   1.103810      7.043   81776930

Filas 2 a 5 y solo la segunda columna

   crecimiento_pib
1         3.757969
2         0.463512
3         0.396996
4         2.180186

len:
14
shape:
(14, 6)
columns:
Index(['anio', 'crecimiento_pib', 'pib_percapita_ppa', 'inflacion',
       'desempleo', 'poblacion'],
      dtype='object')
dtypes:
anio                   int64
crecimiento_pib      float64
pib_percapita_ppa    float64
inflacion            float64
desempleo            float64
poblacion              int64
dtype: object
info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   anio               14 non-null     int64
 1   crecimiento_pib    14 non-null     float64
 2   pib_percapita_ppa  14 non-null     float64
 3   inflacion          14 non-null     float64
 4   desempleo          14 non-null     float64
 5   poblacion          14 non-null     int64
dtypes: float64(4), int64(2)
memory usage: 804.0 bytes

####5

In [46]:
url_otra = "https://restcountries.com/v3.1/all?fields=name,capital,region,subregion,population,area,cca2,cca3,independent,timezones"
respuesta = requests.get(url_otra)

print("Código de respuesta:", respuesta.status_code)

data = respuesta.json()
otra_api = pd.json_normalize(data)

otra_api.head()

Código de respuesta: 200

,cca2,cca3,independent,capital,region,subregion,area,population,timezones,name.common,...,name.nativeName.sag.official,name.nativeName.sag.common,name.nativeName.urd.official,name.nativeName.urd.common,name.nativeName.nep.official,name.nativeName.nep.common,name.nativeName.bos.official,name.nativeName.bos.common,name.nativeName.pov.official,name.nativeName.pov.common
0,ZW,ZWE,True,[Harare],Africa,Southern Africa,390757.0,17073087,[UTC+02:00],Zimbabwe,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,KI,KIR,True,[South Tarawa],Oceania,Micronesia,811.0,120740,"[UTC+12:00, UTC+13:00, UTC+14:00]",Kiribati,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GH,GHA,True,[Accra],Africa,Western Africa,238533.0,33742380,[UTC],Ghana,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KP,PRK,True,[Pyongyang],Asia,Eastern Asia,120538.0,25950000,[UTC+09:00],North Korea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ES,ESP,True,[Madrid],Europe,Southern Europe,505992.0,49315949,"[UTC, UTC+01:00]",Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
otra_api_limpia = otra_api[[
    "cca2", "cca3", "independent", "capital", "region",
    "subregion", "area", "population", "timezones", "name.common"
]]

otra_api_limpia.head()

,cca2,cca3,independent,capital,region,subregion,area,population,timezones,name.common
0,ZW,ZWE,True,[Harare],Africa,Southern Africa,390757.0,17073087,[UTC+02:00],Zimbabwe
1,KI,KIR,True,[South Tarawa],Oceania,Micronesia,811.0,120740,"[UTC+12:00, UTC+13:00, UTC+14:00]",Kiribati
2,GH,GHA,True,[Accra],Africa,Western Africa,238533.0,33742380,[UTC],Ghana
3,KP,PRK,True,[Pyongyang],Asia,Eastern Asia,120538.0,25950000,[UTC+09:00],North Korea
4,ES,ESP,True,[Madrid],Europe,Southern Europe,505992.0,49315949,"[UTC, UTC+01:00]",Spain

In [48]:
print("Primeras 5 filas")
display(otra_api_limpia.head())

print("Últimas 10 filas")
display(otra_api_limpia.tail(10))

print("3 filas aleatorias")
display(otra_api_limpia.sample(min(3, len(otra_api_limpia)), random_state=42))

print("Filas 2 a 5 y solo la segunda columna")
display(otra_api_limpia.iloc[1:5, [1]])

print("len:")
print(len(otra_api_limpia))

print("shape:")
print(otra_api_limpia.shape)

print("columns:")
print(otra_api_limpia.columns)

print("dtypes:")
print(otra_api_limpia.dtypes)

print("info():")
otra_api_limpia.info()

Primeras 5 filas

,cca2,cca3,independent,capital,region,subregion,area,population,timezones,name.common
0,ZW,ZWE,True,[Harare],Africa,Southern Africa,390757.0,17073087,[UTC+02:00],Zimbabwe
1,KI,KIR,True,[South Tarawa],Oceania,Micronesia,811.0,120740,"[UTC+12:00, UTC+13:00, UTC+14:00]",Kiribati
2,GH,GHA,True,[Accra],Africa,Western Africa,238533.0,33742380,[UTC],Ghana
3,KP,PRK,True,[Pyongyang],Asia,Eastern Asia,120538.0,25950000,[UTC+09:00],North Korea
4,ES,ESP,True,[Madrid],Europe,Southern Europe,505992.0,49315949,"[UTC, UTC+01:00]",Spain

Últimas 10 filas

,cca2,cca3,independent,capital,region,subregion,area,population,timezones,name.common
240,CV,CPV,True,[Praia],Africa,Western Africa,4033.0,491233,[UTC-01:00],Cape Verde
241,GD,GRD,True,[St. George's],Americas,Caribbean,344.0,109021,[UTC-04:00],Grenada
242,PK,PAK,True,[Islamabad],Asia,Southern Asia,796095.0,241499431,[UTC+05:00],Pakistan
243,NP,NPL,True,[Kathmandu],Asia,Southern Asia,147181.0,29911840,[UTC+05:45],Nepal
244,BA,BIH,True,[Sarajevo],Europe,Southeast Europe,51209.0,3422000,[UTC+01:00],Bosnia and Herzegovina
245,SS,SSD,True,[Juba],Africa,Middle Africa,619745.0,15786898,[UTC+03:00],South Sudan
246,GW,GNB,True,[Bissau],Africa,Western Africa,36125.0,1781308,[UTC],Guinea-Bissau
247,BJ,BEN,True,[Porto-Novo],Africa,Western Africa,112622.0,13224860,[UTC+01:00],Benin
248,LB,LBN,True,[Beirut],Asia,Western Asia,10452.0,5490000,[UTC+02:00],Lebanon
249,AX,ALA,False,[Mariehamn],Europe,Northern Europe,1580.0,30654,[UTC+02:00],Åland Islands

3 filas aleatorias

,cca2,cca3,independent,capital,region,subregion,area,population,timezones,name.common
142,NF,NFK,False,[Kingston],Oceania,Australia and New Zealand,36.0,2188,[UTC+11:30],Norfolk Island
6,SM,SMR,True,[City of San Marino],Europe,Southern Europe,61.0,34132,[UTC+01:00],San Marino
97,AQ,ATA,False,[],Antarctic,,14000000.0,1300,"[UTC-03:00, UTC+03:00, UTC+05:00, UTC+06:00, U...",Antarctica

Filas 2 a 5 y solo la segunda columna

  cca3
1  KIR
2  GHA
3  PRK
4  ESP

len:
250
shape:
(250, 10)
columns:
Index(['cca2', 'cca3', 'independent', 'capital', 'region', 'subregion', 'area',
       'population', 'timezones', 'name.common'],
      dtype='object')
dtypes:
cca2            object
cca3            object
independent       bool
capital         object
region          object
subregion       object
area           float64
population       int64
timezones       object
name.common     object
dtype: object
info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cca2         250 non-null    object
 1   cca3         250 non-null    object
 2   independent  250 non-null    bool
 3   capital      250 non-null    object
 4   region       250 non-null    object
 5   subregion    250 non-null    object
 6   area         250 non-null    float64
 7   population   250 non-null    int64
 8   timezones    250 non-null    object
 9   name.common  250 non-null    object
dtypes: bool(1), float64(1), int64(1), object(7)
memory usage: 18.0+ KB

## Conclusión

En este taller se trabajó con diferentes fuentes de datos, tanto archivos locales como APIs públicas. Se cargaron, exploraron y describieron los conjuntos de datos usando herramientas de pandas como `head`, `tail`, `sample`, `iloc`, `len`, `shape`, `columns`, `dtypes` e `info`, lo que permitió identificar la estructura y características principales de cada base. esto con apoyo de IA de google