In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
base_path = Path("/content/drive/MyDrive/IA-Economia")

In [4]:

from pathlib import Path

base_path = Path("/content/drive/MyDrive/IA-Economia")
print(base_path.exists())
print(list(base_path.iterdir()))

True
[PosixPath('/content/drive/MyDrive/IA-Economia/07_Exportaciones_2024_Julio.xlsx'), PosixPath('/content/drive/MyDrive/IA-Economia/08_Exportaciones_2024_Agosto.xlsx'), PosixPath('/content/drive/MyDrive/IA-Economia/09_Exportaciones_2024_Septiembre.xlsx'), PosixPath('/content/drive/MyDrive/IA-Economia/UNCTAD_2021-FDI.xlsx'), PosixPath('/content/drive/MyDrive/IA-Economia/Julio 2025.zip'), PosixPath('/content/drive/MyDrive/IA-Economia/Agosto 2025.zip'), PosixPath('/content/drive/MyDrive/IA-Economia/Octubre 2025.zip'), PosixPath('/content/drive/MyDrive/IA-Economia/Septiembre 2025.zip'), PosixPath('/content/drive/MyDrive/IA-Economia/Noviembre 2025.zip'), PosixPath('/content/drive/MyDrive/IA-Economia/Diciembre 2025.zip')]

In [5]:
import zipfile
from pathlib import Path

base_path = Path("/content/drive/MyDrive/IA-Economia")

zips = [
    "Julio 2025.zip",
    "Agosto 2025.zip",
    "Septiembre 2025.zip",
    "Octubre 2025.zip",
    "Noviembre 2025.zip",
    "Diciembre 2025.zip"
]

for zip_name in zips:
    zip_path = base_path / zip_name
    output_folder = base_path / zip_name.replace(".zip", "")

    output_folder.mkdir(exist_ok=True)

    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(output_folder)

    print(f"Descomprimido: {zip_name} -> {output_folder}")

Descomprimido: Julio 2025.zip -> /content/drive/MyDrive/IA-Economia/Julio 2025
Descomprimido: Agosto 2025.zip -> /content/drive/MyDrive/IA-Economia/Agosto 2025
Descomprimido: Septiembre 2025.zip -> /content/drive/MyDrive/IA-Economia/Septiembre 2025
Descomprimido: Octubre 2025.zip -> /content/drive/MyDrive/IA-Economia/Octubre 2025
Descomprimido: Noviembre 2025.zip -> /content/drive/MyDrive/IA-Economia/Noviembre 2025
Descomprimido: Diciembre 2025.zip -> /content/drive/MyDrive/IA-Economia/Diciembre 2025

In [6]:
for carpeta in ["Julio 2025", "Agosto 2025", "Septiembre 2025", "Octubre 2025", "Noviembre 2025", "Diciembre 2025"]:
    ruta = base_path / carpeta
    print(f"\nContenido de {carpeta}:")
    for archivo in ruta.iterdir():
        print("-", archivo.name)

Contenido de Julio 2025:
- DTA
- SAV
- CSV

Contenido de Agosto 2025:
- CSV
- DTA
- SAV

Contenido de Septiembre 2025:
- DTA
- SAV
- CSV

Contenido de Octubre 2025:
- DTA
- SAV
- CSV

Contenido de Noviembre 2025:
- SAV
- DAT
- CSV

Contenido de Diciembre 2025:
- DAT
- SAV
- CSV

In [7]:
for carpeta in ["Julio 2025", "Agosto 2025", "Septiembre 2025", "Octubre 2025", "Noviembre 2025", "Diciembre 2025"]:
    ruta_csv = base_path / carpeta / "CSV"
    print(f"\nCSV dentro de {carpeta}:")
    for archivo in ruta_csv.iterdir():
        print("-", archivo.name)

CSV dentro de Julio 2025:
- Características generales, seguridad social en salud y educación.CSV
- Datos del hogar y la vivienda.CSV
- Fuerza de trabajo.CSV
- Migración.CSV
- No ocupados.CSV
- Ocupados.CSV
- Otras formas de trabajo.CSV
- Otros ingresos e impuestos.CSV

CSV dentro de Agosto 2025:
- Características generales, seguridad social en salud y  educación.CSV
- Datos del hogar y la vivienda.CSV
- Fuerza de trabajo.CSV
- Migración.CSV
- No ocupados.CSV
- Ocupados.CSV
- Otras formas de trabajo.CSV
- Otros ingresos e impuestos.CSV

CSV dentro de Septiembre 2025:
- Características generales, seguridad social en salud y educación.CSV
- Datos del hogar y la vivienda.CSV
- Fuerza de trabajo.CSV
- Migración.CSV
- No ocupados.CSV
- Ocupados.CSV
- Otras formas de trabajo.CSV
- Otros ingresos e impuestos.CSV

CSV dentro de Octubre 2025:
- Características generales, seguridad social en salud y educación.CSV
- Datos del hogar y la vivienda.CSV
- Fuerza de trabajo.CSV
- Migración.CSV
- No ocupados.CSV
- Ocupados.CSV
- Otras formas de trabajo.CSV
- Otros ingresos e impuestos.CSV

CSV dentro de Noviembre 2025:
- Características generales, seguridad social en salud y educación.CSV
- Datos del hogar y la vivienda.CSV
- Fuerza de trabajo.CSV
- Migración.CSV
- No ocupados.CSV
- Ocupados.CSV
- Otras formas de trabajo.CSV
- Otros ingresos e impuestos.CSV

CSV dentro de Diciembre 2025:
- Características generales, seguridad social en salud y educación.CSV
- Datos del hogar y la vivienda.CSV
- Fuerza de trabajo.CSV
- Migración.CSV
- No ocupados.CSV
- Ocupados.CSV
- Otras formas de trabajo.CSV
- Otros ingresos e impuestos.CSV

In [9]:
ruta_julio = base_path / "Julio 2025" / "CSV"

cg = pd.read_csv(
    ruta_julio / "Características generales, seguridad social en salud y educación.CSV",
    low_memory=False,
    encoding="latin1"
)

viv = pd.read_csv(
    ruta_julio / "Datos del hogar y la vivienda.CSV",
    low_memory=False,
    encoding="latin1"
)

ft = pd.read_csv(
    ruta_julio / "Fuerza de trabajo.CSV",
    low_memory=False,
    encoding="latin1"
)

ocu = pd.read_csv(
    ruta_julio / "Ocupados.CSV",
    low_memory=False,
    encoding="latin1"
)

print("CG:", cg.shape)
print("VIV:", viv.shape)
print("FT:", ft.shape)
print("OCU:", ocu.shape)

CG: (68436, 1)
VIV: (24546, 1)
FT: (54630, 1)
OCU: (30153, 1)

In [10]:
ruta_julio = base_path / "Julio 2025" / "CSV"

cg = pd.read_csv(
    ruta_julio / "Características generales, seguridad social en salud y educación.CSV",
    low_memory=False,
    encoding="latin1",
    sep=";"
)

viv = pd.read_csv(
    ruta_julio / "Datos del hogar y la vivienda.CSV",
    low_memory=False,
    encoding="latin1",
    sep=";"
)

ft = pd.read_csv(
    ruta_julio / "Fuerza de trabajo.CSV",
    low_memory=False,
    encoding="latin1",
    sep=";"
)

ocu = pd.read_csv(
    ruta_julio / "Ocupados.CSV",
    low_memory=False,
    encoding="latin1",
    sep=";"
)

print("CG:", cg.shape)
print("VIV:", viv.shape)
print("FT:", ft.shape)
print("OCU:", ocu.shape)

CG: (68436, 55)
VIV: (24546, 49)
FT: (54630, 42)
OCU: (30153, 202)

In [11]:
print(cg.columns.tolist()[:15])
print(viv.columns.tolist()[:15])
print(ft.columns.tolist()[:15])
print(ocu.columns.tolist()[:15])

['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR', 'REGIS', 'AREA', 'CLASE', 'FEX_C18', 'DPTO', 'PT', 'P6016', 'P3271']
['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'HOGAR', 'REGIS', 'AREA', 'CLASE', 'FEX_C18', 'DPTO', 'P4005', 'P4010', 'P4020', 'P4030S1']
['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR', 'REGIS', 'AREA', 'CLASE', 'FEX_C18', 'DPTO', 'FT', 'FFT', 'PET']
['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR', 'REGIS', 'AREA', 'CLASE', 'FEX_C18', 'DPTO', 'FT', 'P3044S2', 'P6440']

In [14]:
print(viv.columns.tolist())

['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'HOGAR', 'REGIS', 'AREA', 'CLASE', 'FEX_C18', 'DPTO', 'P4005', 'P4010', 'P4020', 'P4030S1', 'P4030S1A1', 'P4030S2', 'P4030S3', 'P4030S4', 'P4030S4A1', 'P4030S5', 'P70', 'P5000', 'P5010', 'P5020', 'P5030', 'P5040', 'P5050', 'P5070', 'P5080', 'P5090', 'P5090S1', 'P5100', 'P5110', 'P5130', 'P5140', 'P5222S1', 'P5222S2', 'P5222S3', 'P5222S4', 'P5222S5', 'P5222S6', 'P5222S7', 'P5222S8', 'P5222S8A1', 'P5222S9', 'P5222S10', 'P5222S11', 'P6008']

In [15]:
print(viv[["DIRECTORIO", "SECUENCIA_P"]].head())

   DIRECTORIO  SECUENCIA_P
0     8283143            1
1     8283145            1
2     8283147            1
3     8283149            1
4     8283151            1

In [16]:
julio = cg.merge(
    viv,
    on=["DIRECTORIO", "SECUENCIA_P"],
    how="left",
    suffixes=("", "_VIV")
)

julio = julio.merge(
    ft,
    on=["DIRECTORIO", "SECUENCIA_P", "ORDEN"],
    how="left",
    suffixes=("", "_FT")
)

julio = julio.merge(
    ocu,
    on=["DIRECTORIO", "SECUENCIA_P", "ORDEN"],
    how="left",
    suffixes=("", "_OCU")
)

print(julio.shape)
julio.head()

(68436, 340)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250731,7,2025,8283143,1,1,1,10,NaN,2,...,3.0,NaN,10.0,3.0,NaN,1.0,790000.0,1.0,143.0,9212.0
1,20250731,7,2025,8283143,1,2,1,10,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250731,7,2025,8283145,1,1,1,10,NaN,2,...,3.0,NaN,4.0,8.0,NaN,1.0,1100000.0,1.0,141.0,1311.0
3,20250731,7,2025,8283145,1,2,1,10,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20250731,7,2025,8283145,1,3,1,10,NaN,2,...,3.0,NaN,3.0,3.0,NaN,1.0,820000.0,1.0,141.0,9212.0

In [17]:
def leer_modulo(ruta_archivo):
    return pd.read_csv(
        ruta_archivo,
        low_memory=False,
        encoding="latin1",
        sep=";"
    )

def construir_base_mes(nombre_mes):
    ruta_mes = base_path / nombre_mes / "CSV"

    cg = leer_modulo(ruta_mes / "Características generales, seguridad social en salud y educación.CSV")
    viv = leer_modulo(ruta_mes / "Datos del hogar y la vivienda.CSV")
    ft = leer_modulo(ruta_mes / "Fuerza de trabajo.CSV")
    ocu = leer_modulo(ruta_mes / "Ocupados.CSV")

    base_mes = cg.merge(
        viv,
        on=["DIRECTORIO", "SECUENCIA_P"],
        how="left",
        suffixes=("", "_VIV")
    )

    base_mes = base_mes.merge(
        ft,
        on=["DIRECTORIO", "SECUENCIA_P", "ORDEN"],
        how="left",
        suffixes=("", "_FT")
    )

    base_mes = base_mes.merge(
        ocu,
        on=["DIRECTORIO", "SECUENCIA_P", "ORDEN"],
        how="left",
        suffixes=("", "_OCU")
    )

    base_mes["MES_NOMBRE"] = nombre_mes
    return base_mes

In [19]:
ruta_agosto = base_path / "Agosto 2025" / "CSV"

for archivo in ruta_agosto.iterdir():
    print(repr(archivo.name))

'Características generales, seguridad social en salud y\xa0 educación.CSV'
'Datos del hogar y la vivienda.CSV'
'Fuerza de trabajo.CSV'
'Migración.CSV'
'No ocupados.CSV'
'Ocupados.CSV'
'Otras formas de trabajo.CSV'
'Otros ingresos e impuestos.CSV'

In [20]:
def buscar_archivo(ruta_mes, texto):
    for archivo in ruta_mes.iterdir():
        if texto.lower() in archivo.name.lower():
            return archivo
    raise FileNotFoundError(f"No encontré un archivo que contenga: {texto} en {ruta_mes}")

In [21]:
def leer_modulo(ruta_archivo):
    return pd.read_csv(
        ruta_archivo,
        low_memory=False,
        encoding="latin1",
        sep=";"
    )

def construir_base_mes(nombre_mes):
    ruta_mes = base_path / nombre_mes / "CSV"

    archivo_cg = buscar_archivo(ruta_mes, "Características generales")
    archivo_viv = buscar_archivo(ruta_mes, "Datos del hogar y la vivienda")
    archivo_ft = buscar_archivo(ruta_mes, "Fuerza de trabajo")
    archivo_ocu = buscar_archivo(ruta_mes, "Ocupados")

    cg = leer_modulo(archivo_cg)
    viv = leer_modulo(archivo_viv)
    ft = leer_modulo(archivo_ft)
    ocu = leer_modulo(archivo_ocu)

    base_mes = cg.merge(
        viv,
        on=["DIRECTORIO", "SECUENCIA_P"],
        how="left",
        suffixes=("", "_VIV")
    )

    base_mes = base_mes.merge(
        ft,
        on=["DIRECTORIO", "SECUENCIA_P", "ORDEN"],
        how="left",
        suffixes=("", "_FT")
    )

    base_mes = base_mes.merge(
        ocu,
        on=["DIRECTORIO", "SECUENCIA_P", "ORDEN"],
        how="left",
        suffixes=("", "_OCU")
    )

    base_mes["MES_NOMBRE"] = nombre_mes
    return base_mes

In [23]:
import unicodedata

def limpiar_texto(texto):
    texto = texto.lower().strip()
    texto = unicodedata.normalize("NFKD", texto)
    texto = "".join(c for c in texto if not unicodedata.combining(c))
    return texto

def buscar_archivo(ruta_mes, texto):
    texto_limpio = limpiar_texto(texto)

    for archivo in ruta_mes.iterdir():
        nombre_limpio = limpiar_texto(archivo.name)
        if texto_limpio in nombre_limpio:
            return archivo

    disponibles = [a.name for a in ruta_mes.iterdir()]
    raise FileNotFoundError(f"No encontré un archivo que contenga: {texto}. Disponibles: {disponibles}")

In [24]:
def leer_modulo(ruta_archivo):
    return pd.read_csv(
        ruta_archivo,
        low_memory=False,
        encoding="latin1",
        sep=";"
    )

def construir_base_mes(nombre_mes):
    ruta_mes = base_path / nombre_mes / "CSV"

    archivo_cg = buscar_archivo(ruta_mes, "generales")
    archivo_viv = buscar_archivo(ruta_mes, "hogar y la vivienda")
    archivo_ft = buscar_archivo(ruta_mes, "fuerza de trabajo")
    archivo_ocu = buscar_archivo(ruta_mes, "ocupados")

    print(f"\nProcesando {nombre_mes}")
    print("CG  ->", archivo_cg.name)
    print("VIV ->", archivo_viv.name)
    print("FT  ->", archivo_ft.name)
    print("OCU ->", archivo_ocu.name)

    cg = leer_modulo(archivo_cg)
    viv = leer_modulo(archivo_viv)
    ft = leer_modulo(archivo_ft)
    ocu = leer_modulo(archivo_ocu)

    base_mes = cg.merge(
        viv,
        on=["DIRECTORIO", "SECUENCIA_P"],
        how="left",
        suffixes=("", "_VIV")
    )

    base_mes = base_mes.merge(
        ft,
        on=["DIRECTORIO", "SECUENCIA_P", "ORDEN"],
        how="left",
        suffixes=("", "_FT")
    )

    base_mes = base_mes.merge(
        ocu,
        on=["DIRECTORIO", "SECUENCIA_P", "ORDEN"],
        how="left",
        suffixes=("", "_OCU")
    )

    base_mes["MES_NOMBRE"] = nombre_mes
    return base_mes

In [25]:
meses = [
    "Julio 2025",
    "Agosto 2025",
    "Septiembre 2025",
    "Octubre 2025",
    "Noviembre 2025",
    "Diciembre 2025"
]

bases = []

for mes in meses:
    df_mes = construir_base_mes(mes)
    print("Shape:", df_mes.shape)
    bases.append(df_mes)

Procesando Julio 2025
CG  -> Características generales, seguridad social en salud y educación.CSV
VIV -> Datos del hogar y la vivienda.CSV
FT  -> Fuerza de trabajo.CSV
OCU -> No ocupados.CSV
Shape: (68436, 176)

Procesando Agosto 2025
CG  -> Características generales, seguridad social en salud y  educación.CSV
VIV -> Datos del hogar y la vivienda.CSV
FT  -> Fuerza de trabajo.CSV
OCU -> No ocupados.CSV
Shape: (68577, 176)

Procesando Septiembre 2025
CG  -> Características generales, seguridad social en salud y educación.CSV
VIV -> Datos del hogar y la vivienda.CSV
FT  -> Fuerza de trabajo.CSV
OCU -> No ocupados.CSV
Shape: (68263, 176)

Procesando Octubre 2025
CG  -> Características generales, seguridad social en salud y educación.CSV
VIV -> Datos del hogar y la vivienda.CSV
FT  -> Fuerza de trabajo.CSV
OCU -> No ocupados.CSV
Shape: (68710, 176)

Procesando Noviembre 2025
CG  -> Características generales, seguridad social en salud y educación.CSV
VIV -> Datos del hogar y la vivienda.CSV
FT  -> Fuerza de trabajo.CSV
OCU -> No ocupados.CSV
Shape: (68582, 176)

Procesando Diciembre 2025
CG  -> Características generales, seguridad social en salud y educación.CSV
VIV -> Datos del hogar y la vivienda.CSV
FT  -> Fuerza de trabajo.CSV
OCU -> No ocupados.CSV
Shape: (66559, 176)

In [26]:
geih_2025 = pd.concat(bases, ignore_index=True)
print("Base consolidada:", geih_2025.shape)
geih_2025.head()

Base consolidada: (409127, 176)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P9460,P1519,P1883,P7422,P7422S1,OFICIO1_C8,OFICIO2_C8,RAMA2D_D_R4,RAMA4D_D_R4,MES_NOMBRE
0,20250731,7,2025,8283143,1,1,1,10,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Julio 2025
1,20250731,7,2025,8283143,1,2,1,10,NaN,2,...,NaN,2.0,NaN,2.0,NaN,.,.,NaN,.,Julio 2025
2,20250731,7,2025,8283145,1,1,1,10,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Julio 2025
3,20250731,7,2025,8283145,1,2,1,10,NaN,2,...,2.0,2.0,NaN,2.0,NaN,.,9111,97.0,9700,Julio 2025
4,20250731,7,2025,8283145,1,3,1,10,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Julio 2025

In [27]:
geih_2025["RAMAD_R"] = (
    geih_2025["RAMA4D_D_R4"]
    .astype(str)
    .str.replace(".0", "", regex=False)
    .str.strip()
    .str[:4]
)

geih_2025[["RAMA4D_D_R4", "RAMAD_R"]].head(10)

  RAMA4D_D_R4 RAMAD_R
0         NaN     nan
1           .       .
2         NaN     nan
3        9700    9700
4         NaN     nan
5         NaN     nan
6         NaN     nan
7        9700    9700
8         NaN     nan
9           .       .

In [28]:
geih_2025["RAMAD_R"].value_counts(dropna=False).head(20)

RAMAD_R
nan     266201
.        58618
9700      7752
8121      4604
5611      4572
8530      3380
4111      3165
5619      2442
4771      2406
1410      2170
4711      2032
8412      1997
8610      1959
4921      1886
0123      1747
9602      1104
0161       939
5511       861
1081       843
0141       833
Name: count, dtype: int64

In [29]:
ruta_ciiu = base_path / "2025-01-14 Correlativa CIIU Rev4.xlsx"
print(ruta_ciiu.exists())

False

In [31]:
for archivo in base_path.iterdir():
    if archivo.suffix.lower() in [".xlsx", ".xls"]:
        print(repr(archivo.name))

'07_Exportaciones_2024_Julio.xlsx'
'08_Exportaciones_2024_Agosto.xlsx'
'09_Exportaciones_2024_Septiembre.xlsx'
'UNCTAD_2021-FDI.xlsx'

In [37]:
for archivo in base_path.iterdir():
    nombre = archivo.name.lower()
    if "ciiu" in nombre or "correlativa" in nombre:
        print("Encontrado:", repr(archivo.name))

In [38]:
ruta_ciiu = base_path / "NOMBRE_EXACTO_DEL_ARCHIVO.xlsx"
print(ruta_ciiu.exists())

False

In [39]:
ruta_ciiu = None

for archivo in base_path.iterdir():
    nombre = archivo.name.lower()
    if archivo.suffix.lower() == ".xlsx" and ("ciiu" in nombre or "correlativa" in nombre):
        ruta_ciiu = archivo
        break

print(ruta_ciiu)

None

In [41]:
for archivo in base_path.iterdir():
    print(repr(archivo.name))

'07_Exportaciones_2024_Julio.xlsx'
'08_Exportaciones_2024_Agosto.xlsx'
'09_Exportaciones_2024_Septiembre.xlsx'
'UNCTAD_2021-FDI.xlsx'
'Julio 2025.zip'
'Agosto 2025.zip'
'Octubre 2025.zip'
'Septiembre 2025.zip'
'Noviembre 2025.zip'
'Diciembre 2025.zip'
'Julio 2025'
'Agosto 2025'
'Septiembre 2025'
'Octubre 2025'
'Noviembre 2025'
'Diciembre 2025'

In [42]:
for archivo in base_path.iterdir():
    if archivo.suffix.lower() in [".xlsx", ".xls"]:
        print(repr(archivo.name))

'07_Exportaciones_2024_Julio.xlsx'
'08_Exportaciones_2024_Agosto.xlsx'
'09_Exportaciones_2024_Septiembre.xlsx'
'UNCTAD_2021-FDI.xlsx'

In [43]:
ruta_ciiu = base_path / "AQUI_PEGA_EL_NOMBRE_EXACTO.xlsx"
print(ruta_ciiu.exists())

False

In [45]:
ruta_ciiu = base_path / "UNCTAD_2021-FDI.xlsx" # Reemplaza con el nombre exacto de tu archivo
xls = pd.ExcelFile(ruta_ciiu)
print(xls.sheet_names)

['MySheet']

In [46]:
for archivo in base_path.iterdir():
    if archivo.suffix.lower() in [".xlsx", ".xls"]:
        print(repr(archivo.name))

'07_Exportaciones_2024_Julio.xlsx'
'08_Exportaciones_2024_Agosto.xlsx'
'09_Exportaciones_2024_Septiembre.xlsx'
'UNCTAD_2021-FDI.xlsx'

In [47]:
for archivo in base_path.iterdir():
    nombre = archivo.name.lower()
    if archivo.suffix.lower() in [".xlsx", ".xls"] and (
        "ciiu" in nombre or "correlativa" in nombre or "rev4" in nombre
    ):
        print(repr(archivo.name))

In [49]:
for archivo in base_path.iterdir():
    if archivo.suffix.lower() in [".xlsx", ".xls"]:
        print(repr(archivo.name))

'07_Exportaciones_2024_Julio.xlsx'
'08_Exportaciones_2024_Agosto.xlsx'
'09_Exportaciones_2024_Septiembre.xlsx'
'UNCTAD_2021-FDI.xlsx'

In [50]:
for archivo in base_path.iterdir():
    nombre = archivo.name.lower()
    if archivo.suffix.lower() in [".xlsx", ".xls"] and (
        "ciiu" in nombre or "correlativa" in nombre or "rev4" in nombre
    ):
        print("CANDIDATO:", repr(archivo.name))

In [51]:
CANDIDATO: '2025-01-14 Correlativa CIIU Rev4.xlsx'

In [53]:
ruta_ciiu = None

for archivo in base_path.iterdir():
    nombre = archivo.name.lower()
    if archivo.suffix.lower() in [".xlsx", ".xls"] and (
        "ciiu" in nombre or "correlativa" in nombre or "rev4" in nombre
    ):
        ruta_ciiu = archivo
        print("Encontrado:", ruta_ciiu)
        break

In [57]:
candidatos = []

for archivo in base_path.rglob("*"):
    if archivo.is_file() and archivo.suffix.lower() in [".xlsx", ".xls"]:
        nombre = archivo.name.lower()
        if "ciiu" in nombre or "correlativa" in nombre or "rev4" in nombre:
            candidatos.append(archivo)

for i, c in enumerate(candidatos):
    print(i, c)

In [59]:
for archivo in base_path.iterdir():
    if archivo.suffix.lower() in [".xlsx", ".xls"]:
        print(repr(archivo.name))

'07_Exportaciones_2024_Julio.xlsx'
'08_Exportaciones_2024_Agosto.xlsx'
'09_Exportaciones_2024_Septiembre.xlsx'
'UNCTAD_2021-FDI.xlsx'

In [61]:
for archivo in base_path.iterdir():
    print(repr(archivo.name))

'07_Exportaciones_2024_Julio.xlsx'
'08_Exportaciones_2024_Agosto.xlsx'
'09_Exportaciones_2024_Septiembre.xlsx'
'UNCTAD_2021-FDI.xlsx'
'Julio 2025.zip'
'Agosto 2025.zip'
'Octubre 2025.zip'
'Septiembre 2025.zip'
'Noviembre 2025.zip'
'Diciembre 2025.zip'
'Julio 2025'
'Agosto 2025'
'Septiembre 2025'
'Octubre 2025'
'Noviembre 2025'
'Diciembre 2025'

In [64]:
geih_2025.to_csv(base_path / "GEIH_2025_consolidada_sin_cruces.csv", index=False, encoding="utf-8-sig")
print("Guardada.")

Guardada.

In [67]:
for archivo in base_path.iterdir():
    print(repr(archivo.name))

'07_Exportaciones_2024_Julio.xlsx'
'08_Exportaciones_2024_Agosto.xlsx'
'09_Exportaciones_2024_Septiembre.xlsx'
'UNCTAD_2021-FDI.xlsx'
'Julio 2025.zip'
'Agosto 2025.zip'
'Octubre 2025.zip'
'Septiembre 2025.zip'
'Noviembre 2025.zip'
'Diciembre 2025.zip'
'Julio 2025'
'Agosto 2025'
'Septiembre 2025'
'Octubre 2025'
'Noviembre 2025'
'Diciembre 2025'
'GEIH_2025_consolidada_sin_cruces.csv'